function [Track_file] = importTrackMate(filePattern, dataLines)
%IMPORTFILE Import data from a text file
%  SPOTSSTATISTICS = IMPORTTRACKMATE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SPOTSSTATISTICS = IMPORTTRACKMATE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Spotsstatistics = importTrackMate("Z:\Documents\Data Analysis\SPT_LiveScript\Spots_statistics.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Apr-2020 18:09:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 21);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "TRACK_ID", "QUALITY", "POSITION_X", "POSITION_Y", "POSITION_Z", "POSITION_T", "FRAME", "RADIUS", "VISIBILITY", "MANUAL_COLOR", "MEAN_INTENSITY", "MEDIAN_INTENSITY", "MIN_INTENSITY", "MAX_INTENSITY", "TOTAL_INTENSITY", "STANDARD_DEVIATION", "ESTIMATED_DIAMETER", "CONTRAST", "SNR"];
opts.SelectedVariableNames = ["TRACK_ID", "QUALITY", "POSITION_X", "POSITION_Y", "POSITION_Z", "POSITION_T", "FRAME", "RADIUS", "VISIBILITY", "MANUAL_COLOR", "MEAN_INTENSITY", "MEDIAN_INTENSITY", "MIN_INTENSITY", "MAX_INTENSITY", "TOTAL_INTENSITY", "STANDARD_DEVIATION", "ESTIMATED_DIAMETER", "CONTRAST", "SNR"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
%opts = setvaropts(opts, ["Var1", "Var2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2"], "EmptyFieldRule", "auto");


% Import the data
Track_file = readtable(filePattern, opts);
end